 
services:
  backend:
    build:
      context: .
    restart: on-failure
    ports:
      - 8081:8080
    environment:
        - POSTGRES_HOST=${POSTGRES_HOST}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - SPRING_SECURITY_SECRET_KEY=${SPRING_SECURITY_SECRET_KEY}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
  postgresdb:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
