 
services:
  postgresdb:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
