spring:
    frontend-url: ${FRONTEND_URL}

    datasource:
        port: ${POSTGRES_PORT}
        host: ${POSTGRES_HOST}
        database: ${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD:}
        aws-db-secret-arn: ${AWS_DB_SECRET_ARN:}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        databse-platform: org.hibernate.dialect.PostgreSQLDialect
    security:
        secret-key: ${SPRING_SECURITY_SECRET_KEY}

    google:
        client-id: ${GOOGLE_CLIENT_ID}
        client-secret: ${GOOGLE_CLIENT_SECRET}
        redirect-uri: ${GOOGLE_REDIRECT_URI}

aws:
    region: ${AWS_REGION:us-east-1}
